// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLoIJdJpLPqyS6xZLXOpILvR8hg5ha7XM',
    appId: '1:297826711204:web:66707569f34f1a09105831',
    messagingSenderId: '297826711204',
    projectId: 'authenticated-user-dashboard',
    authDomain: 'authenticated-user-dashboard.firebaseapp.com',
    storageBucket: 'authenticated-user-dashboard.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdM2WCYJeRVP5NdifKOv35lbHRAoN0weo',
    appId: '1:297826711204:android:a1be45e5b4497d83105831',
    messagingSenderId: '297826711204',
    projectId: 'authenticated-user-dashboard',
    storageBucket: 'authenticated-user-dashboard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbAd3UztCOmoEINZal7tAnZXLnxdj3uYM',
    appId: '1:297826711204:ios:95eb34647d41ef30105831',
    messagingSenderId: '297826711204',
    projectId: 'authenticated-user-dashboard',
    storageBucket: 'authenticated-user-dashboard.firebasestorage.app',
    iosBundleId: 'com.example.aunthenticatedUserDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbAd3UztCOmoEINZal7tAnZXLnxdj3uYM',
    appId: '1:297826711204:ios:95eb34647d41ef30105831',
    messagingSenderId: '297826711204',
    projectId: 'authenticated-user-dashboard',
    storageBucket: 'authenticated-user-dashboard.firebasestorage.app',
    iosBundleId: 'com.example.aunthenticatedUserDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLoIJdJpLPqyS6xZLXOpILvR8hg5ha7XM',
    appId: '1:297826711204:web:e51fac73340498c2105831',
    messagingSenderId: '297826711204',
    projectId: 'authenticated-user-dashboard',
    authDomain: 'authenticated-user-dashboard.firebaseapp.com',
    storageBucket: 'authenticated-user-dashboard.firebasestorage.app',
  );

}