// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD36YLWJeJX24DyPTWhCzeEfFWDDUqEKo',
    appId: '1:875121348047:web:cc69eaf03cdc8a7b0ed6ba',
    messagingSenderId: '875121348047',
    projectId: 'authenticated-user-dashb-ab95b',
    authDomain: 'authenticated-user-dashb-ab95b.firebaseapp.com',
    storageBucket: 'authenticated-user-dashb-ab95b.firebasestorage.app',
    measurementId: 'G-ECJ5V16392',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8AVk_5DWJU4rpvPjoemKdFXGZHvHFh_w',
    appId: '1:875121348047:android:4f9c83289d2d30470ed6ba',
    messagingSenderId: '875121348047',
    projectId: 'authenticated-user-dashb-ab95b',
    storageBucket: 'authenticated-user-dashb-ab95b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbSrokyZnvqfOKn49ce6BP3JsFeAGMyzI',
    appId: '1:875121348047:ios:cbcdd0b47dc094af0ed6ba',
    messagingSenderId: '875121348047',
    projectId: 'authenticated-user-dashb-ab95b',
    storageBucket: 'authenticated-user-dashb-ab95b.firebasestorage.app',
    iosBundleId: 'com.example.aunthenticatedUserDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbSrokyZnvqfOKn49ce6BP3JsFeAGMyzI',
    appId: '1:875121348047:ios:cbcdd0b47dc094af0ed6ba',
    messagingSenderId: '875121348047',
    projectId: 'authenticated-user-dashb-ab95b',
    storageBucket: 'authenticated-user-dashb-ab95b.firebasestorage.app',
    iosBundleId: 'com.example.aunthenticatedUserDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD36YLWJeJX24DyPTWhCzeEfFWDDUqEKo',
    appId: '1:875121348047:web:37e498a0374c17620ed6ba',
    messagingSenderId: '875121348047',
    projectId: 'authenticated-user-dashb-ab95b',
    authDomain: 'authenticated-user-dashb-ab95b.firebaseapp.com',
    storageBucket: 'authenticated-user-dashb-ab95b.firebasestorage.app',
    measurementId: 'G-157LJYY6VY',
  );
}
